---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudappi-api
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: front-end
          image: joseberrocal/cloudappi-codechallenge:latest
          ports:
            - containerPort: 5000
